# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Zar")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.Browse1 = QtWidgets.QPushButton(self.centralwidget)
        self.Browse1.setGeometry(QtCore.QRect(620, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Browse1.setFont(font)
        self.Browse1.setObjectName("Browse1")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 140, 281, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(250, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Zar")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAutoFillBackground(True)
        self.label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.Browse2 = QtWidgets.QPushButton(self.centralwidget)
        self.Browse2.setGeometry(QtCore.QRect(620, 210, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Browse2.setFont(font)
        self.Browse2.setObjectName("Browse2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(312, 210, 281, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Request = QtWidgets.QPushButton(self.centralwidget)
        self.Request.setGeometry(QtCore.QRect(390, 340, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Request.setFont(font)
        self.Request.setObjectName("Request")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Browse1.clicked.connect(self.Browse1.deleteLater) # type: ignore
        self.Browse2.clicked.connect(self.Browse2.deleteLater) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "To:"))
        self.Browse1.setText(_translate("MainWindow", "Browse"))
        self.label1.setText(_translate("MainWindow", "From:"))
        self.Browse2.setText(_translate("MainWindow", "Browse"))
        self.Request.setText(_translate("MainWindow", "Request"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
